require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PrzedmiotyController do

  # This should return the minimal set of attributes required to create a valid
  # Przedmiot. As you add validations to Przedmiot, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PrzedmiotyController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all przedmioty as @przedmioty" do
      przedmiot = Przedmiot.create! valid_attributes
      get :index, {}, valid_session
      assigns(:przedmioty).should eq([przedmiot])
    end
  end

  describe "GET show" do
    it "assigns the requested przedmiot as @przedmiot" do
      przedmiot = Przedmiot.create! valid_attributes
      get :show, {:id => przedmiot.to_param}, valid_session
      assigns(:przedmiot).should eq(przedmiot)
    end
  end

  describe "GET new" do
    it "assigns a new przedmiot as @przedmiot" do
      get :new, {}, valid_session
      assigns(:przedmiot).should be_a_new(Przedmiot)
    end
  end

  describe "GET edit" do
    it "assigns the requested przedmiot as @przedmiot" do
      przedmiot = Przedmiot.create! valid_attributes
      get :edit, {:id => przedmiot.to_param}, valid_session
      assigns(:przedmiot).should eq(przedmiot)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Przedmiot" do
        expect {
          post :create, {:przedmiot => valid_attributes}, valid_session
        }.to change(Przedmiot, :count).by(1)
      end

      it "assigns a newly created przedmiot as @przedmiot" do
        post :create, {:przedmiot => valid_attributes}, valid_session
        assigns(:przedmiot).should be_a(Przedmiot)
        assigns(:przedmiot).should be_persisted
      end

      it "redirects to the created przedmiot" do
        post :create, {:przedmiot => valid_attributes}, valid_session
        response.should redirect_to(Przedmiot.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved przedmiot as @przedmiot" do
        # Trigger the behavior that occurs when invalid params are submitted
        Przedmiot.any_instance.stub(:save).and_return(false)
        post :create, {:przedmiot => {}}, valid_session
        assigns(:przedmiot).should be_a_new(Przedmiot)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Przedmiot.any_instance.stub(:save).and_return(false)
        post :create, {:przedmiot => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested przedmiot" do
        przedmiot = Przedmiot.create! valid_attributes
        # Assuming there are no other przedmioty in the database, this
        # specifies that the Przedmiot created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Przedmiot.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => przedmiot.to_param, :przedmiot => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested przedmiot as @przedmiot" do
        przedmiot = Przedmiot.create! valid_attributes
        put :update, {:id => przedmiot.to_param, :przedmiot => valid_attributes}, valid_session
        assigns(:przedmiot).should eq(przedmiot)
      end

      it "redirects to the przedmiot" do
        przedmiot = Przedmiot.create! valid_attributes
        put :update, {:id => przedmiot.to_param, :przedmiot => valid_attributes}, valid_session
        response.should redirect_to(przedmiot)
      end
    end

    describe "with invalid params" do
      it "assigns the przedmiot as @przedmiot" do
        przedmiot = Przedmiot.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Przedmiot.any_instance.stub(:save).and_return(false)
        put :update, {:id => przedmiot.to_param, :przedmiot => {}}, valid_session
        assigns(:przedmiot).should eq(przedmiot)
      end

      it "re-renders the 'edit' template" do
        przedmiot = Przedmiot.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Przedmiot.any_instance.stub(:save).and_return(false)
        put :update, {:id => przedmiot.to_param, :przedmiot => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested przedmiot" do
      przedmiot = Przedmiot.create! valid_attributes
      expect {
        delete :destroy, {:id => przedmiot.to_param}, valid_session
      }.to change(Przedmiot, :count).by(-1)
    end

    it "redirects to the przedmioty list" do
      przedmiot = Przedmiot.create! valid_attributes
      delete :destroy, {:id => przedmiot.to_param}, valid_session
      response.should redirect_to(przedmioty_url)
    end
  end

end
